name: Flujo de Trabajo MicroservicioCICD
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Tarea01 actions/checkout@v4
        uses: actions/checkout@v4
      - name: Instalar Java 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Mave Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify